$(document).ready(function () {
    
    //montando legislacao

	var x;
	var i = 1;
	var legislacoes = {

		leg_1: {
			id: '1',
			ano: '2018',
			lei: 'Lei nº 13.769/2018',
			ementa: 'DISCIPLINA O REGIME DE CUMPRIMENTO DE PENA	PRIVATIVA DE LIBERDADE DA MULHER GESTANTE OU QUE FOR MÃE OU RESPONSÁVEL POR CRIANÇAS OU PESSOAS COM DEFICIÊNCIA, BEM COMO SOBRE A SUBSTITUIÇÃO DA PRISÃO PREVENTIVA POR PRISÃO DOMICILIAR DAS MULHERES NA MESMA SITUAÇÃO.',
			autora: 'Senadora Simone Tebet',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/132359'
		},

		leg_2: {
			id: '2',
			ano: '2018',
			ementa: 'INSTITUI O ANO DE 2018 COMO O ANO DE VALORIZAÇÃO E DEFESA DOS DIREITOS HUMANOS DA PESSOA IDOSA, EM ALUSÃO À RATIFICAÇÃO PELO BRASIL DA CONVENÇÃO INTERAMERICANA SOBRE A PROTEÇÃO DOS DIREITOS HUMANOS DOS IDOSOS. NOVA EMENTA: INSTITUI O ANO DE VALORIZAÇÃO E DEFESA DOS DIREITOS HUMANOS DA PESSOA IDOSA, EM ALUSÃO À CONVENÇÃO INTERAMERICANA SOBRE A PROTEÇÃO DOS DIREITOS HUMANOS DOS IDOSOS.',
			autora: 'Deputada Leandre',
			lei: 'Lei nº 13.646/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2166298',
		},
		leg_3: {
			id: '3',
			ano: '2018',
			ementa: 'ACRESCENTA O ART. 4º- A À LEI Nº 12.732, DE 22 DE NOVEMBRO DE 2012, PARA ESTABELECER A NOTIFICAÇÃO E O REGISTRO COMPULSÓRIO DE AGRAVOS E EVENTOS EM SAÚDE RELACIONADOS ÀS NEOPLASIAS. NOVA EMENTA: ALTERA A LEI Nº 12.732, DE 22 DE NOVEMBRO DE 2012, PARA ESTABELECER A NOTIFICAÇÃO COMPULSÓRIA DE AGRAVOS E EVENTOS EM SAÚDE RELACIONADOS ÀS NEOPLASIAS, E A LEI Nº 12.662, DE 5 DE JUNHO DE 2012, PARA ESTABELECER A NOTIFICAÇÃO COMPULSÓRIA DE MALFORMAÇÕES CONGÊNITAS.',
			autora: 'Deputada Carmen Zanotto ',
			lei: 'Lei nº 13.685/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2150301',
		},
		leg_4: {
			id: '4',
			ano: '2018',
			ementa: 'CONFERE AO MUNICÍPIO DE SALINAS, NO ESTADO DE MINAS GERAIS, O TÍTULO DE CAPITAL NACIONAL DA CACHAÇA.',
			autora: 'Deputada Raquel Muniz',
			lei: 'Lei nº 13.773/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=21502',
		},
		leg_5: {
			id: '5',
			ano: '2018',
			ementa: 'DISPÕE SOBRE A PERDA DO PODER FAMILIAR EM CASO DE FEMINICÍDIO, DE LESÕES GRAVÍSSIMAS E ABUSO SEXUAL CONTRA FILHOS. NOVA EMENTA: ALTERA O DECRETO-LEI Nº 2.848, DE 7 DE DEZEMBRO DE 1940 (CÓDIGO PENAL), E AS LEIS NºS 8.069, DE 13 DE JULHO DE 1990, E 10.406, DE 10 DE JANEIRO DE 2002 (CÓDIGO CIVIL), PARA DISPOR SOBRE HIPÓTESES DE PERDA DE PODER FAMILIAR. ',
			autora: 'Deputada Laura Carneiro',
			lei: 'Lei nº 13.715/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2141477',
		},
		leg_6: {
			id: '6',
			ano: '2018',
			ementa: 'INSTITUI, NO ÂMBITO DO SENADO FEDERAL, A COMENDA DE INCENTIVO À CULTURA LUÍS DA CÂMARA CASCUDO.',
			autora: 'Senadora Fátima Bezerra',
			lei: 'Resolução do Senado Federal nº 7/2018',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/128899',
		},
		leg_7: {
			id: '7',
			ano: '2017',
			ementa: 'SUSPENDE, NOS TERMOS DO ART. 52, INCISO X, DA CONSTITUIÇÃO FEDERAL, A EXECUÇÃO DO DO ARTIGO 1º DA LEI Nº 8.540/92, QUE DEU NOVA REDAÇÃO AOS ARTIGOS 12, INCISOS V E VII, 25, INCISOS I E II, E 30, INCISO IV, DA LEI Nº 8.212/91, COM A REDAÇÃO ATUALIZADA ATÉ A LEI Nº 9.528/97.',
			autora: 'Senadora Kátia Abreu',
			lei: 'Resolução do Senado Federal nº 15/2017',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/128872',
		},
		leg_8: {
			id: '8',
			ano: '2019',
			ementa: 'CONFERE NOVA REDAÇÃO AO ARTIGO 1520 DA LEI 10.406 DE 10 DE JANEIRO DE 2002, DE MODO A SUPRIMIR AS EXCEÇÕES LEGAIS AO CASAMENTO INFANTIL. NOVA EMENTA: CONFERE NOVA REDAÇÃO AO ART. 1.520 DA LEI Nº 10.406, DE 10 DE JANEIRO DE 2002 (CÓDIGO CIVIL), PARA SUPRIMIR AS EXCEÇÕES LEGAIS PERMISSIVAS DO CASAMENTO INFANTIL.',
			autora: 'Deputada Laura Carneiro ',
			lei: 'Lei nº 13.811/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2125584',
		},
		leg_9: {
			id: '9',
			ano: '2017',
			ementa: 'ALTERA O REGIMENTO INTERNO DO SENADO FEDERAL PARA REDEFINIR AS ATRIBUIÇÕES E AS DENOMINAÇÕES DAS COMISSÕES DE MEIO AMBIENTE, DEFESA DO CONSUMIDOR E FISCALIZAÇÃO E CONTROLE (CMA) E DE TRANSPARÊNCIA E GOVERNANÇA PÚBLICA (CTG).',
			autora: 'Senadora Rose De Freitas',
			lei: 'Resolução do Senado Federal nº 3/2017',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/128197',
		},
		leg_10: {
			id: '10',
			ano: '2019',
			ementa: 'INSCREVE O NOME DE ANTÔNIO VICENTE MENDES MACIEL, O ANTÔNIO CONSELHEIRO, NO LIVRO DOS HERÓIS DA PÁTRIA ',
			autora: 'Deputada Luizianne Lins ',
			lei: 'Lei nº 13.829/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2121697',
		},
		leg_11: {
			id: '11',
			ano: '2016',
			ementa: 'PRORROGA O PRAZO PARA O EXERCÍCIO DA AUTORIZAÇÃO ESTABELECIDO NO ART. 4º DA RESOLUÇÃO Nº 37, DE 19 DE NOVEMBRO DE 2014.',
			autora: 'Senadora Lídice Da Mata',
			lei: 'Resolução do Senado Federal nº 36/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/126643',
		},
		leg_12: {
			id: '12',
			ano: '2017',
			ementa: 'ALTERA A REDAÇÃO DO §2º DO ART. 4º DA RESOLUÇÃO Nº 1, DE 1970 - CN (REGIMENTO COMUM), PARA AMPLIAR O NÚMERO DE VICE-LÍDERES DO GOVERNO NO CONGRESSO',
			autora: '<b>Senadora Rose De Freitas</b>, Deputado Wellington Roberto',
			lei: 'Resolução do Congresso Nacional nº 1/2017',
			link: 'https://www.congressonacional.leg.br/materias/pesquisa/-/materia/126530',
		},
		leg_13: {
			id: '13',
			ano: '2018',
			ementa: 'ACRESCENTA INCISOS IX E X AO ART. 12 DA LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, PARA INCLUIR O COMBATE A TODAS AS FORMAS DE VIOLÊNCIA E A PROMOÇÃO DE CULTURA DE PAZ ENTRE AS INCUMBÊNCIAS DOS ESTABELECIMENTOS DE ENSINO.',
			autora: 'Deputada Keiko Ota ',
			lei: 'Lei nº 13.663/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2091857',
		},
		leg_14: {
			id: '14',
			ano: '2019',
			ementa: 'INSCREVE O NOME DE NELSON DE SOUZA CARNEIRO NO LIVRO DOS HERÓIS DA PÁTRIA',
			autora: 'Deputada Maria Helena',
			lei: 'Lei nº 13.852/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2084950',
		},
		leg_15: {
			id: '15',
			ano: '2018',
			ementa: 'INSTITUI A POLÍTICA NACIONAL DE LEITURA E ESCRITA.',
			autora: 'Senadora Fátima Bezerra',
			lei: 'Lei nº 13.696/2018',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/125776',
		},
		leg_16: {
			id: '16',
			ano: '2018',
			ementa: 'ALTERA A LEI Nº 10.446, DE 8 DE MAIO DE 2002, PARA ACRESCENTAR ATRIBUIÇÃO À POLÍCIA FEDERAL NO QUE CONCERNE À INVESTIGAÇÃO DE CRIMES PRATICADOS POR MEIO DA REDE MUNDIAL DE COMPUTADORES QUE DIFUNDAM CONTEÚDO MISÓGINO, OU SEJA, AQUELES QUE PROPAGAM O ÓDIO OU A AVERSÃO ÀS MULHERES.',
			autora: 'Deputada Luizianne Lins',
			lei: 'Lei nº 13.642/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2078694',
		},
		leg_17: {
			id: '17',
			ano: '2017',
			ementa: 'INSCREVE O NOME DE ZULEIKA ANGEL JONES NO LIVRO DOS HERÓIS DA PÁTRIA.',
			autora: 'Deputada Jandira Feghali',
			lei: 'Lei nº 13.433/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2077391',
		},
		leg_18: {
			id: '18',
			ano: '2017',
			ementa: 'ACRESCENTA UM PARÁGRAFO ÚNICO AO ART. 292, DO DECRETO-LEI Nº 3.689, DE 3 DE OUTUBRO DE 1941 - CÓDIGO DE PROCESSO PENAL - VEDANDO O USO DE ALGEMAS EM MULHERES GRÁVIDAS DURANTE O PARTO E DURANTE A FASE DE PUERPÉRIO IMEDIATO NOVA EMENTA: ACRESCENTA PARÁGRAFO ÚNICO AO ART. 292 DO DECRETO-LEI Nº 3.689, DE 3 DE OUTUBRO DE 1941 (CÓDIGO DE PROCESSO PENAL), PARA VEDAR O USO DE ALGEMAS EM MULHERES GRÁVIDAS DURANTE O PARTO E EM MULHERES DURANTE A FASE DE PUERPÉRIO IMEDIATO.',
			autora: 'Deputada Angela Albino',
			lei: 'Lei nº 13.434/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2075874',
		},
		leg_19: {
			id: '19',
			ano: '2016',
			ementa: 'ALTERA O REGULAMENTO ADMINISTRATIVO DO SENADO FEDERAL PARA CRIAR O OBSERVATÓRIO DA MULHER CONTRA A VIOLÊNCIA E AS ATRIBUIÇÕES DE ANALISTA LEGISLATIVO, ESPECIALIDADES PESQUISADOR DE OPINIÃO E ESTATÍSTICO.',
			autora: 'Senadora Simone Tebet',
			lei: 'Resolução do Senado Federal nº 7/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/124496',
		},
		leg_20: {
			id: '20',
			ano: '2016',
			ementa: 'ALTERA O REGIMENTO INTERNO DO SENADO FEDERAL PARA CONFERIR AO INSTITUTO DATASENADO A ATRIBUIÇÃO DE AUXILIAR NA PRODUÇÃO DE ANÁLISES RELACIONADAS À AVALIAÇÃO DE POLÍTICAS PÚBLICAS A CARGO DAS COMISSÕES PERMANENTES DO SENADO FEDERAL.',
			autora: 'Senadora Simone Tebet ',
			lei: 'Resolução do Senado Federal nº 6 de 28/03/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/124497',
		},
		leg_21: {
			id: '21',
			ano: '2017',
			ementa: 'ESTABELECE O SISTEMA DE GARANTIA DE DIREITOS DE CRIANÇAS E ADOLESCENTES VÍTIMAS E TESTEMUNHAS DE VIOLÊNCIA, E DÁ OUTRAS PROVIDÊNCIAS. NOVA EMENTA: ESTABELECE O SISTEMA DE GARANTIA DE DIREITOS DE CRIANÇAS E ADOLESCENTES VÍTIMAS E TESTEMUNHAS DE VIOLÊNCIA; ALTERA A LEI Nº 8.069, DE 13 DE JULHO DE 1990; E DÁ OUTRAS ...',
			autora: 'Deputada Maria Do Rosário, Eliziane Gama, Josi Nunes,  Margarida Salomão, Mainha; Maria Helena e outros',
			lei: 'Lei nº 13.431/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2057263',
		},
		leg_22: {
			id: '22',
			ano: '2017',
			ementa: 'INSTITUI O MÊS DE AGOSTO COMO O MÊS DO ALEITAMENTO MATERNO.',
			autora: 'Deputada Dulce Miranda ',
			lei: 'Lei nº 13.435/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2025540',
		},
		leg_23: {
			id: '23',
			ano: '2019',
			ementa: 'INSCREVE O NOME DE DANDARA DOS PALMARES E DE LUIZA MAHIN NO LIVRO DOS HERÓIS DA PÁTRIA.',
			autora: 'Deputada Tia Eron ',
			lei: 'Lei nº 13.816/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1738816',
		},
		leg_24: {
			id: '24',
			ano: '2017',
			ementa: 'DISPÕE SOBRE A PRORROGAÇÃO DOS PRAZOS DE VIGÊNCIA DAS BOLSAS DE ESTUDO CONCEDIDAS POR AGÊNCIAS DE FOMENTO PARA PROTEÇÃO ÀS MULHERES BOLSISTAS EM FUNÇÃO DE MATERNIDADE. NOVA EMENTA: DISPÕE SOBRE A PRORROGAÇÃO DOS PRAZOS DE VIGÊNCIA DAS BOLSAS DE ESTUDO CONCEDIDAS POR AGÊNCIAS DE FOMENTO À PESQUISA NOS CASOS DE MATERNIDADE E DE ADOÇÃO.',
			autora: 'Deputada Alice Portugal',
			lei: 'Lei nº 13.536/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1733047',
		},
		leg_25: {
			id: '25',
			ano: '2018',
			ementa: 'DISPÕE SOBRE AÇÕES DO OUTUBRO ROSA',
			autora: 'Deputada Carmen Zanotto; Dr. Jorge Silva',
			lei: 'Lei nº 13.733/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1733001',
		},
		leg_26: {
			id: '26',
			ano: '2016',
			ementa: 'INSTITUI O ANO DE 2016 COMO O ANO DO EMPODERAMENTO DA MULHER NA POLÍTICA E NO ESPORTE.',
			autora: 'Senadora Fátima Bezerra, Senador Romário, Senadora Vanessa Grazziotin',
			lei: 'Lei nº 13.272/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/122586',
		},
		leg_27: {
			id: '27',
			ano: '2018',
			ementa: 'REGULAMENTA A PROFISSÃO DE ESTETICISTA, COSMETÓLOGO E TÉCNICO EM ESTÉTICA. NOVA EMENTA: REGULAMENTA AS PROFISSÕES DE ESTETICISTA, QUE COMPREENDE O ESTETICISTA E COSMETÓLOGO, E DE TÉCNICO EM ESTÉTICA.',
			autora: 'Deputada Soraya Santos',
			lei: 'Lei nº 13.643/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1570719',
		},
		leg_28: {
			id: '28',
			ano: '2018',
			ementa: 'CONFERE AO MUNICÍPIO DE NOVA VENEZA O TÍTULO DE "CAPITAL NACIONAL DA GASTRONOMIA TÍPICA ITALIANA".',
			autora: 'Deputada Geovania De Sá',
			lei: 'Lei nº 13.678/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1514520',
		},
		leg_29: {
			id: '29',
			ano: '2018',
			ementa: 'INSTITUI O DIA 27 DE NOVEMBRO COMO DIA NACIONAL DE EDUCAÇÃO A DISTÂNCIA.',
			autora: 'Deputada Professora Dorinha Seabra Rezende',
			lei: 'Lei nº 13.620/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=1295999',
		},
		leg_30: {
			id: '30',
			ano: '2018',
			ementa: 'INSTITUI O DIA NACIONAL DO ZOOTECNISTA.',
			autora: 'Deputada Júlia Marinho ',
			lei: 'Lei nº 13.596/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=969165',
		},
		leg_31: {
			id: '31',
			ano: '2017',
			ementa: 'DISPÕE SOBRE A REALIZAÇÃO ANUAL DE ATIVIDADES DIRECIONADAS AO ENFRENTAMENTO DO HIV/AIDS DURANTE O MÊS DE DEZEMBRO.',
			autora: 'Deputada Erika Kokay e Outros',
			lei: 'Lei nº 13.504/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=964469',
		},
		leg_32: {
			id: '32',
			ano: '2016',
			ementa: 'ALTERA A LEI Nº 11.346, DE 15 DE SETEMBRO DE 2006, A FIM DE PREVER, NO CONCEITO DE SEGURANÇA ALIMENTAR E NUTRICIONAL, A AMPLIAÇÃO DAS CONDIÇÕES DE ACESSO AOS ALIMENTOS POR MEIO DAS MEDIDAS QUE MITIGUEM O RISCO DE ESCASSEZ DE ÁGUA POTÁVEL, BEM COMO A FORMAÇÃO DE ESTOQUES REGULADORES E ESTRATÉGICOS DE ALIMENTOS.',
			autora: 'Senadora Ângela Portela',
			lei: 'Lei nº 13.362/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/119864',
		},
		leg_33: {
			id: '33',
			ano: '2019',
			ementa: 'ACRESCENTA DISPOSITIVO AO ART. 12 DA LEI Nº 11.340, DE 7 DE AGOSTO DE 2006, PARA TORNAR OBRIGATÓRIA A INFORMAÇÃO SOBRE A CONDIÇÃO DE PESSOA COM DEFICIÊNCIA DA MULHER VÍTIMA DE AGRESSÃO DOMÉSTICA OU FAMILIAR E DÁ OUTRAS PROVIDÊNCIAS.',
			autora: 'Deputada Rosangela Gomes',
			lei: 'Lei nº 13.836/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=946623',
		},
		leg_34: {
			id: '34',
			ano: '2016',
			ementa: 'DISPÕE SOBRE A RESPONSABILIDADE CIVIL DE NOTÁRIOS E REGISTRADORES.',
			autora: 'Deputada Erika Kokay',
			lei: 'Lei nº 13.286/2016.',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=946132',
		},
		leg_35: {
			id: '35',
			ano: '2015',
			ementa: 'ALTERA A RESOLUÇÃO Nº 2, DE 2001, PARA PERMITIR QUE HOMENS TAMBÉM SEJAM AGRACIADOS COM O DIPLOMA BERTHA LUTZ. ',
			autora: 'Senadora Vanessa Grazziotin',
			lei: 'Resolução do Senado Federal nº 1/2015',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/118522',
		},
		leg_36: {
			id: '36',
			ano: '2017',
			ementa: 'INSTITUI NO ÂMBITO DO SENADO FEDERAL A FRENTE PARLAMENTAR EM DEFESA DA AMAZÔNIA LEGAL.',
			autora: 'Senadora Vanessa Grazziotin',
			lei: 'Resolução do Senado Federal nº 24/2017',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/118157',
		},
		leg_37: {
			id: '37',
			ano: '2016',
			ementa: 'INSTITUI O GRUPO PARLAMENTAR BRASIL-INDONÉSIA.',
			autora: 'Senadora Vanessa Grazziotin ',
			lei: 'Resolução do Senado Federal nº 32/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/118130',
		},
		leg_38: {
			id: '38',
			ano: '2017',
			ementa: 'INSTITUI O DIA 9 DE FEVEREIRO COMO O DIA NACIONAL DO CERCO DA LAPA.',
			autora: 'Deputada Rosane Ferreira e Outros.',
			lei: 'Lei nº 13.570/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=599478',
		},
		leg_39: {
			id: '39',
			ano: '2017',
			ementa: 'DENOMINA CAPITAL DO SEMIÁRIDO A CIDADE DE MOSSORÓ (RN).',
			autora: 'Deputada Sandra Rosado',
			lei: 'Lei nº 13.568/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=588788',
		},
		leg_40: {
			id: '40',
			ano: '2019',
			ementa: 'ALTERA O INCISO VIII DO ART. 12 DA LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, PARA OBRIGAR A NOTIFICAÇÃO DE FALTAS ESCOLARES AO CONSELHO TUTELAR E DEMAIS AUTORIDADES QUANDO ATINGIR O PERCENTUAL DE TRINTA POR CENTO. NOVA EMENTA: ALTERA DISPOSITIVO DA LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, PARA OBRIGAR A NOTIFICAÇÃO DE FALTAS ESCOLARES AO CONSELHO TUTELAR QUANDO SUPERIORES A 30% (TRINTA POR CENTO) DO PERCENTUAL PERMITIDO EM LEI.',
			autora: 'Deputada Keiko Ota',
			lei: 'Lei nº 13.803/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=588296',
		},
		leg_41: {
			id: '41',
			ano: '2014',
			ementa: 'ALTERA A REDAÇÃO DO ART. 159 DA CONSTITUIÇÃO FEDERAL, PARA AUMENTAR EM DOIS PONTOS PERCENTUAIS O REPASSE DO IR E DO IPI PARA O FUNDO DE PARTICIPAÇÃO DOS MUNICÍPIOS (FPM).',
			autora: 'Senadora Ana Amélia e Outros',
			lei: 'Emenda Constitucional nº 84/2014',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/114042',
		},
		leg_42: {
			id: '42',
			ano: '2017',
			ementa: 'INSTITUI O DIA NACIONAL DA AGROECOLOGIA.',
			autora: 'Deputada Luci Choinacki ',
			lei: 'Lei nº 13.565/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=584066',
		},
		leg_43: {
			id: '43',
			ano: '2017',
			ementa: 'ALTERA ARTIGOS DA LEI Nº 9.503/97 QUE INSTITUI O CÓDIGO NACIONAL DE TRÂNSITO BRASILEIRO E DÁ OUTRAS PROVIDÊNCIAS. NOVA EMENTA: ALTERA DISPOSITIVOS DA LEI Nº 9.503, DE 23 DE SETEMBRO DE 1997 - CÓDIGO DE TRÂNSITO BRASILEIRO, PARA DISPOR SOBRE CRIMES COMETIDOS NA DIREÇÃO DE VEÍCULOS AUTOMOTORES.',
			autora: 'Deputada Keiko Ota',
			lei: 'Lei nº 13.546/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=576699',
		},
		leg_44: {
			id: '44',
			ano: '2019',
			ementa: 'ALTERA A LEI DA COMUNICAÇÃO AUDIOVISUAL DE ACESSO CONDICIONADO, LEI Nº 12.485, DE 12 DE SETEMBRO DE 2011, INCLUINDO COMO DIREITO DOS ASSINANTES A POSSIBILIDADE DE CANCELAMENTO DOS SERVIÇOS DE TV POR ASSINATURA PESSOALMENTE OU PELA INTERNET.',
			autora: 'Deputada Flávia Morais ',
			lei: 'Lei nº 13.828/2019',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=568765',
		},
		leg_45: {
			id: '45',
			ano: '2013',
			ementa: 'CRIA A PROCURADORIA ESPECIAL DA MULHER DO SENADO FEDERAL.',
			autora: 'Senadora Vanessa Grazziotin',
			lei: 'Resolução do Senado Federal nº 9/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/110432',
		},
		leg_46: {
			id: '46',
			ano: '2018',
			ementa: 'INCLUI O DIA INTERNACIONAL DO DIREITO À VERDADE NO CALENDÁRIO NACIONAL DE DATAS COMEMORATIVAS.',
			autora: 'Deputada Luiza Erundina, Erika Kokay, Janete Capiberibe e outros.',
			lei: 'Lei nº 13.605/2018',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=564103',
		},
		leg_47: {
			id: '47',
			ano: '2012',
			ementa: 'INSTITUI O PROGRAMA DE CULTURA DO TRABALHADOR; CRIA O VALE-CULTURA; ALTERA AS LEIS NºS 8.212, DE 24 DE JULHO DE 1991, E 7.713, DE 22 DE DEZEMBRO DE 1988, E A CONSOLIDAÇÃO DAS LEIS DO TRABALHO-CLT, APROVADA PELO DECRETO- LEI Nº 5.452, DE 1º DE MAIO DE 1943; E DÁ OUTRAS PROVIDÊNCIAS.',
			autora: 'Deputada Manuela D´ávila E Outros',
			lei: 'Lei nº 12.761/2012',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=559088',
		},
		leg_48: {
			id: '48',
			ano: '2014',
			ementa: 'CONFERE AO MUNICÍPIO DE CARLOS BARBOSA, NO RIO GRANDE DO SUL, O TÍTULO DE CAPITAL NACIONAL DO FUTSAL.',
			autora: 'Senadora Ana Amélia',
			lei: 'Emenda Constitucional nº 84/2014',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/107266',
		},
		leg_49: {
			id: '49',
			ano: '2017',
			ementa: 'ALTERA A LEI Nº 6.088, DE 16 DE JULHO DE 1974, PARA INCLUIR O VALE DO RIO VAZA-BARRIS NA ÁREA DE ATUAÇÃO DA COMPANHIA DE DESENVOLVIMENTO DO VALE DO SÃO FRANCISCO (CODEVASF), E DÁ OUTRAS PROVIDÊNCIAS.',
			autora: 'Senadora Lídice Da Mata e Senador Antonio Carlos Valadares',
			lei: 'Lei nº 13.481/2017',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/105467',
		},
		leg_50: {
			id: '50',
			ano: '2012',
			ementa: 'PRORROGA O PRAZO PARA O EXERCÍCIO DA AUTORIZAÇÃO ESTABELECIDO NO ART. 4º DA RESOLUÇÃO Nº 46, DE 31 DE AGOSTO DE 2010.',
			autora: 'Senadora Lídice Da Mata, Senador Walter Pinheiro',
			lei: 'Resolução do Senado Federal nº 9/2012',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/104740',
		},
		leg_51: {
			id: '51',
			ano: '2012',
			ementa: 'ALTERA A RESOLUÇÃO Nº 42, DE 2010, QUE CRIA O PROGRAMA SENADO JOVEM BRASILEIRO, PARA MODIFICAR CRITÉRIOS DE PARTICIPAÇÃO DOS ESTUDANTES.',
			autora: 'Senadora Vanessa Grazziotin e Senador Jorge Viana',
			lei: 'Resolução do Senado Federal nº 48/2012',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/104233',
		},
		leg_52: {
			id: '52',
			ano: '2013',
			ementa: 'INSTITUI NO SENADO FEDERAL A COMENDA DORINA GOUVEIA NOWILL E DÁ OUTRAS PROVIDÊNCIAS.',
			autora: 'Senadora Lídice Da Mata',
			lei: 'Resolução do Senado Federal nº 34/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/102693',
		},
		leg_53: {
			id: '53',
			ano: '2013',
			ementa: 'INSTITUI NO SENADO FEDERAL A COMENDA SENADOR ABDIAS NASCIMENTO E DÁ OUTRAS PROVIDÊNCIAS.',
			autora: 'Senadora Lídice Da Mata, Senador Paulo Paim',
			lei: 'Resolução do Senado Federal nº 47/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/102588',
		},
		leg_54: {
			id: '54',
			ano: '2013',
			ementa: 'ALTERA O ART. 134 DA CONSTITUIÇÃO FEDERAL.',
			autora: 'Senadora Vanessa Grazziotin',
			lei: 'Emenda Constitucional nº 74/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/101807',
		},
		leg_55: {
			id: '55',
			ano: '2017',
			ementa: 'ALTERA A LEI Nº 8.069, DE 13 DE JULHO DE 1990 (ESTATUTO DA CRIANÇA E DO ADOLESCENTE), PARA TORNAR OBRIGATÓRIA A ADOÇÃO, PELO SISTEMA ÚNICO DE SAÚDE, DE PROTOCOLO QUE ESTABELEÇA PADRÕES PARA A AVALIAÇÃO DE RISCOS PARA O DESENVOLVIMENTO PSÍQUICO DAS CRIANÇAS.',
			autora: 'Senadora Ângela Portela',
			lei: 'Lei nº 13.438/2017',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/101400',
		},
		leg_56: {
			id: '56',
			ano: '2016',
			ementa: 'ALTERA A LEI Nº 11.664, DE 29 DE ABRIL DE 2008, QUE DISPÕE SOBRE A EFETIVAÇÃO DE AÇÕES DE SAÚDE QUE ASSEGUREM A PREVENÇÃO, A DETECÇÃO, O TRATAMENTO E O SEGUIMENTO DOS CÂNCERES DO COLO UTERINO E DE MAMA, NO ÂMBITO DO SISTEMA ÚNICO DE SAÚDE - SUS, PARA ASSEGURAR O ATENDIMENTO ÀS MULHERES PORTADORAS DE DEFICIÊNCIA.',
			autora: 'Senadora Ana Amélia',
			lei: 'Lei nº 13.362/2016',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/101215',
		},
		leg_57: {
			id: '57',
			ano: '2013',
			ementa: 'DENOMINA "ENGENHEIRO VASCO FILHO" O TRECHO DA BR-324 QUE LIGA OS MUNICÍPIOS DE SALVADOR E FEIRA DE SANTANA, NA BAHIA.',
			autora: 'Senadora Lídice Da Mata',
			lei: 'Lei nº 12.827/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/99257',
		},
		leg_58: {
			id: '58',
			ano: '2013',
			ementa: 'DISCIPLINA O PAGAMENTO DA AJUDA DE CUSTO DOS MEMBROS DO CONGRESSO NACIONAL.',
			autora: 'Senadora Gleisi Hoffmann ',
			lei: 'Decreto Legislativo nº 210/2013',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/98971',
		},
		leg_59: {
			id: '59',
			ano: '2017',
			ementa: 'INSTITUI O DIA NACIONAL DOS ROSACRUZES, A SER COMEMORADO, ANUALMENTE, NO DIA 02 DE AGOSTO.',
			autora: 'Deputada Elcione Barbalho',
			lei: 'Lei nº 13.583/2017',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=485904',
		},
		leg_60: {
			id: '60',
			ano: '2011',
			ementa: 'DECLARA NILO PEÇANHA PATRONO DA EDUCAÇÃO PROFISSIONAL E TECNOLÓGICA.',
			autora: 'Senadora Fátima Bezerra',
			lei: 'Lei nº 12.417/2011',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/97514',
		},
		leg_61: {
			id: '61',
			ano: '2015',
			ementa: 'INSTITUI A SEMANA NACIONAL DA DOAÇÃO DE LEITE HUMANO, A SER COMEMORADA SEMESTRALMENTE.',
			autora: 'Senadora Marisa Serrano',
			lei: 'Lei nº 13.227/2015',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/97020',
		},
		
		leg_63: {
			id: '63',
			ano: '2012',
			ementa: 'CONFERE AO MUNICÍPIO DE SORRISO, NO ESTADO DE MATO GROSSO, O TÍTULO DE CAPITAL NACIONAL DO AGRONEGÓCIO.',
			autora: 'Senadora Serys Slhessarenko',
			lei: 'Lei nº 12.724/2012',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/96814',
		},
		leg_64: {
			id: '64',
			ano: '2019',
			ementa: 'ACRESCENTA DISPOSITIVO À LEI Nº 8.069, DE 13 DE JULHO DE 1990, QUE DISPÕE SOBRE O ESTATUTO DA CRIANÇA E DO ADOLESCENTE E DÁ OUTRAS PROVIDÊNCIAS, PARA INSTITUIR A SEMANA NACIONAL DE PREVENÇÃO À GRAVIDEZ ADOLESCENTE NÃO PLANEJADA.',
			autora: 'Senadora Marisa Serrano',
			lei: 'Lei nº 13.798/2019',
			link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/95512',
		},

		
			leg_66: {
				id: '66',
				ano: '2012',
				ementa: 'ALTERA O ART. 193 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO - CLT, APROVADA PELO DECRETO-LEI Nº 5.452, DE 1º DE MAIO DE 1943, A FIM DE REDEFINIR OS CRITÉRIOS PARA CARACTERIZAÇÃO DAS ATIVIDADES OU OPERAÇÕES PERIGOSAS.',
				autora: 'Senadora Vanessa Grazziotin ',
				lei: 'Lei nº 12.740/2012',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/93785',
			},
			leg_67: {
				id: '67',
				ano: '2012',
				ementa: 'INSTITUI O DIA 12 DE AGOSTO COMO O DIA NACIONAL DOS DIREITOS HUMANOS.',
				autora: 'Senadora Rose De Freitas ES MDB 16/10/2009',
				lei: 'Lei nº 12.641/2012',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/93661',
			},
			leg_68: {
				id: '68',
				ano: '2015',
				ementa: 'INSTITUI O DIA 20 DE JANEIRO COMO DIA NACIONAL DA PARTEIRA TRADICIONAL. ',
				autora: 'Senadora Rose De Freitas ',
				lei: 'Lei nº 13.100/2015',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/93678',
			},
			leg_69: {
				id: '69',
				ano: '2013',
				ementa: 'DISPÕE SOBRE A DENOMINAÇÃO DO NOVO PRÉDIO DA ADMINISTRAÇÃO DA FACULDADE DE DIREITO, NO CAMPUS DA UNIVERSIDADE FEDERAL DO AMAZONAS, NA CIDADE DE MANAUS.',
				autora: 'Senadora Vanessa Grazziotin ',
				lei: 'Lei nº 12.882/2013',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/90006',
			},
			leg_70: {
				id: '70',
				ano: '2014',
				ementa: 'DISPÕE SOBRE A CRIAÇÃO DO "DIA NACIONAL DA MULHER NEGRA" E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Senadora Serys Slhessarenko ',
				lei: 'Lei nº 12.987/2014',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/89384',
			},
			leg_71: {
				id: '71',
				ano: '2012',
				ementa: 'DENOMINA "FERROVIA DORIVAL RORIZ GUEDES COELHO" O TRECHO DA FERROVIA NORTE-SUL SITUADO NO ESTADO DO TOCANTINS.',
				autora: 'Senadora Kátia Abreu ',
				lei: 'Lei nº 12.672/2012',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/89309',
			},
			leg_72: {
				id: '72',
				ano: '2010',
				ementa: 'INSTITUI O DIA 20 DE JANEIRO COMO O DIA NACIONAL DO FARMACÊUTICO.',
				autora: 'Senadora Vanessa Grazziotin ',
				lei: 'Lei nº 12.338/2010',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/87286',
			},
			leg_73: {
				id: '73',
				ano: '2011',
				ementa: 'INSTITUI O DIA NACIONAL DA AQÜICULTURA',
				autora: 'Senadora Ideli Salvatti ',
				lei: 'Lei nº 12.531/2011',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/86495',
			},
			leg_74: {
				id: '74',
				ano: '2008',
				ementa: 'ALTERA A LEI Nº 5.917, DE 10 DE SETEMBRO DE 1973, QUE APROVA O PLANO NACIONAL DE VIAÇÃO, DE MODO A INCLUIR, NA RELAÇÃO DESCRITIVA DAS RODOVIAS DO SISTEMA RODOVIÁRIO NACIONAL, O ACESSO DA BR-116 AO AEROPORTO DO PLANALTO SERRANO, NO MUNICÍPIO DE CORREIA PINTO, NO  ESTADO DE SANTA CATARINA.',
				autora: 'Senadora Ideli Salvatti',
				lei: 'Lei nº 11.880/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/83709',
			},
			leg_75: {
				id: '75',
				ano: '2011',
				ementa: 'ALTERA A LEI Nº 5.917, DE 10 DE SETEMBRO DE 1973, QUE "APROVA O PLANO NACIONAL DE VIAÇÃO", DEMODO A INCLUIR, NA RELAÇÃO DESCRITIVA DAS RODOVIAS DO SISTEMA RODOVIÁRIO FEDERAL, O ACESSO DA RODOVIA BR-101 AO AEROPORTO REGIONAL SUL, NO MUNICÍPIO DE JAGUARUNA, NO ESTADO DE SANTA CATARINA.',
				autora: 'Senadora Ideli Salvatti ',
				lei: 'Lei nº 12.531/2011',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/86495',
			},
			leg_76: {
				id: '76',
				ano: '2017',
				ementa: 'DISPÕE SOBRE NORMAS GERAIS DE SEGURANÇA EM ASAS DE ESPETÁCULOS E SIMILARES. NOVA EMENTA: ESTABELECE DIRETRIZES GERAIS SOBRE MEDIDAS DE PREVENÇÃO E COMBATE A INCÊNDIO E A DESASTRES EM ESTABELECIMENTOS, EDIFICAÇÕES E ÁREAS DE REUNIÃO DE PÚBLICO; ALTERA AS LEIS NºS 8.078, DE 11 DE SETEMBRO DE 1990, E 10.406, DE 10 DE JANEIRO DE 2002 - CÓDIGO CIVIL; E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Elcione Barbalho',
				lei: 'Lei nº 13.425/2017 ',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=367329',
			},
			leg_77: {
				id: '77',
				ano: '2009',
				ementa: 'INSCREVE O NOME DE ANA NÉRI NO "LIVRO DOS HERÓIS DA PÁTRIA". ',
				autora: 'Senadora Serys Slhessarenko ',
				lei: 'Lei nº 12.105/2009',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/81301',
			},
			leg_78: {
				id: '78',
				ano: '2009',
				ementa: 'CRIA O RASTREAMENTO DA PRODUÇÃO E CONSUMO DE MEDICAMENTOS POR MEIO DO CONTROLE ELETRÔNICO POR CÓDIGOS DE BARRA.',
				autora: 'Senadora Vanessa Grazziotin ',
				lei: 'Lei nº 11.903/2009',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/80423',
			},
			leg_79: {
				id: '79',
				ano: '2016',
				ementa: 'DISPÕE SOBRE A PROIBIÇÃO DE REVISTA ÍNTIMA DE FUNCIONÁRIAS NOS LOCAIS DE TRABALHO.',
				autora: 'Deputada Alice Portugal',
				lei: 'Lei nº 13.271/2016',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=346188',
			},
			leg_80: {
				id: '80',
				ano: '2008',
				ementa: 'INSTITUI O DIA 4 DE DEZEMBRO COMO O "DIA NACIONAL DO PERITO CRIMINAL".',
				autora: 'Senadora Serys Slhessarenko',
				lei: 'Lei nº 11.654/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/78353',
			},
			leg_81: {
				id: '81',
				ano: '2013',
				ementa: 'DISPÕE SOBRE A GRATUIDADE DOS ATOS DE REGISTRO, PELAS ASSOCIAÇÕES DE MORADORES, NECESSÁRIOS À ADAPTAÇÃO ESTATUTÁRIA AO CÓDIGO CIVIL E PARA FINS DE ENQUADRAMENTO DESSAS ENTIDADES COMO ORGANIZAÇÕES DA SOCIEDADE CIVIL DE INTERESSE PÚBLICO.',
				autora: 'Senadora Serys Slhessarenko ',
				lei: 'Lei nº 12.879/2013',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/77490',
			},
			leg_84: {
				id: '84',
				ano: '2007',
				ementa: 'INSTITUI O DIA 4 DE OUTUBRO COMO O "DIA NACIONAL DO AGENTE COMUNITÁRIO DE SAÚDE". ',
				autora: 'Senadora Lúcia Vânia ',
				lei: 'Lei nº 11.585/2007',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/75388',
			},
			leg_85: {
				id: '85',
				ano: '2010',
				ementa: 'DENOMINA "AEROPORTO INTERNACIONAL DE BELÉM - JÚLIO CEZAR RIBEIRO DE SOUZA" O AEROPORTO DA CIDADE DE BELÉM, NO ESTADO DO PARÁ.',
				autora: 'Senadora Ana Júlia Carepa ',
				lei: 'Lei nº 12.228/2010',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/75219',
			},
			leg_86: {
				id: '86',
				ano: '2005',
				ementa: 'INSTITUI O DIA 3 DE DEZEMBRO COMO O DIA NACIONAL DE COMBATE À PIRATARIA E À BIOPIRATARIA.',
				autora: 'Senadora Vanessa Grazziotin',
				lei: 'Lei nº 11.203/2005',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/74739',
			},
			leg_87: {
				id: '87',
				ano: '2007',
				ementa: 'INSTITUI O DIA NACIONAL DE COMBATE AO TRABALHO INFANTIL.',
				autora: 'Senadora Lúcia Vânia ',
				lei: 'Lei nº 11.542/2007',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/74179',
			},
			leg_88: {
				id: '88',
				ano: '2012',
				ementa: 'DETERMINA O EMPREGO OBRIGATÓRIO DA FLEXÃO DE GÊNERO PARA NOMEAR PROFISSÃO OU GRAU EM DIPLOMAS.',
				autora: 'Senadora Serys Slhessarenko ',
				lei: 'Lei nº 12.605/2012',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/72413',
			},
			leg_91: {
				id: '91',
				ano: '2008',
				ementa: 'DISPÕE SOBRE A CRIAÇÃO DO DIA NACIONAL DO TEATRO PARA A INFÂNCIA E JUVENTUDE.',
				autora: 'Senadora Fátima Cleide',
				lei: 'Lei nº 11.722/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/70617',
			},
			leg_92: {
				id: '92',
				ano: '2008',
				ementa: 'INSTITUI O DIA NACIONAL DA MAMOGRAFIA.',
				autora: 'Senadora Lúcia Vânia',
				lei: 'Lei nº 11.695/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/70603',
			},
			leg_93: {
				id: '93',
				ano: '2014',
				ementa: 'ALTERA OS ARTS. 17 E 18 DA LEI Nº 9.656, DE 3 DE JUNHO DE 1998, QUE DISPÕE SOBRE OS PLANOS E SEGUROS PRIVADOS DE ASSISTÊNCIA À SAÚDE, PARA TORNAR OBRIGATÓRIA A EXISTÊNCIA DE CONTRATOS ESCRITOS ENTRE OPERADORAS DOS REFERIDOS PLANOS E SEUS PRESTADORES DE SERVIÇOS.',
				autora: 'Senadora Lúcia Vânia',
				lei: 'Lei nº 13.003/2014',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/70604',
			},
			leg_94: {
				id: '94',
				ano: '2008',
				ementa: 'DÁ O NOME DE ARQUIVO CORA CORALINA AO ARQUIVO DO SENADO FEDERAL.',
				autora: 'Senadora Serys Slhessarenko',
				lei: 'Senado Federal nº 37/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/65397',
			},
			leg_95: {
				id: '95',
				ano: '2008',
				ementa: 'TRANSFORMA A ESTAÇÃO ECOLÓGICA DE ANAVILHANAS, CRIADA PELO DECRETO Nº 86061, DE 2 DE JUNHO DE 1981, EM PARQUE NACIONAL DE ANAVILHANAS.',
				autora: 'Senadora Serys Slhessarenko',
				lei: 'Lei nº 11.799/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/60490',
			},
			leg_96: {
				id: '96',
				ano: '2003',
				ementa: 'ACRESCENTA O NOME DO PROFESSOR MILTON SANTOS À ATUAL DENOMINAÇÃO DO INSTITUTO BRASILEIRO DE GEOGRAFIA ESTATÍSTICA - IBGE.',
				autora: 'Deputada Marinha Raupp',
				lei: 'Lei nº 11.159/2003',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=117481',
			},
			leg_97: {
				id: '97',
				ano: '2012',
				ementa: 'INSTITUI O SALÁRIO ADICIONAL DE PERICULOSIDADE PARA OS VIGILANTES E EMPREGADOS EM TRANSPORTE DE VALORES. NOVA EMENTA: ALTERA O ART. 193 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO - CLT, APROVADA PELO DECRETO-LEI Nº 5.452, DE 1º DE MAIO DE 1943, A FIM DE REDEFINIR OS CRITÉRIOS PARA CARACTERIZAÇÃO DAS ATIVIDADES OU OPERAÇÕES PERIGOSAS.',
				autora: 'Deputada Vanessa Grazziotin',
				lei: 'Lei nº 12.740/2012',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=116409',
			},
			leg_98: {
				id: '98',
				ano: '2010',
				ementa: 'DEFINE PRIORIDADES PARA A DESTINAÇÃO DE PRODUTOS DE ORIGEM ANIMAL E VEGETAL APREENDIDOS NA FORMA DA LEI.',
				autora: 'Deputada Edna Macedo ',
				lei: 'Lei nº 12.341/2010',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=110768',
			},
			leg_99: {
				id: '99',
				ano: '2007',
				ementa: 'DISPÕE SOBRE A DENOMINAÇÃO DO AEROPORTO FEDERAL DE ALEGRETE, NO ESTADO DO RIO GRANDE O SUL PARA AEROPORTO FEDERAL GAUDÊNCIO MACHADO RAMOS.',
				autora: 'Deputada Maria Do Rosário ',
				lei: 'Lei nº 11.624/2007',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=109085',
			},
			leg_100: {
				id: '100',
				ano: '2018',
				ementa: 'DISPÕE SOBRE A OBRIGATORIEDADE DE EMISSORAS DE RADIODIFUSÃO TRANSMITIREM O PROGRAMA OFICIAL DOS PODERES DA REPÚBLICA. NOVA EMENTA: ALTERA A LEI Nº 4.117, DE 27 DE AGOSTO DE 1962, PARA DISPOR SOBRE O HORÁRIO DE RETRANSMISSÃO OBRIGATÓRIA DO PROGRAMA OFICIAL DOS PODERES DA REPÚBLICA PELAS EMISSORAS DE RADIODIFUSÃO ... ',
				autora: 'Deputada Perpétua Almeida ',
				lei: 'Lei nº 13.644/2018 ',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=109150',
			},
			leg_101: {
				id: '101',
				ano: '2008',
				ementa: 'ALTERA A LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, MODIFICADA PELA LEI Nº 10.639, DE 09 DE JANEIRO DE 2003, QUE ESTABELECE AS DIRETRIZES E BASES DA EDUCAÇÃO NACIONAL, PARA INCLUIR, NO CURRÍCULO OFICIAL DA REDE DE ENSINO, A OBRIGATORIEDADE DA TEMÁTICA "HÍSTÓRIA E CULTURA AFRO-BRASILEIRA E INDÍGENA".',
				autora: 'Deputada Mariângela Duarte',
				lei: 'Lei nº 11.645/2008',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=107240',
			},
			leg_102: {
				id: '102',
				ano: '2008',
				ementa: 'DEFINE AS DIRETRIZES DA POLÍTICA DE PREVENÇÃO E ATENÇÃO INTEGRAL À SAÚDE DA PESSOA PORTADORA DE HEPATITE, EM TODAS AS SUAS FORMAS, NO ÂMBITO DO SISTEMA ÚNICO DE SAÚDE (SUS) E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Mariângela Duarte',
				lei: 'Lei nº 11.645/2008',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=107238',
			},
			leg_103: {
				id: '103',
				ano: '2004',
				ementa: 'DECLARA PATRONO DA GEOGRAFIA NACIONAL O GEÓGRAFO MILTON SANTOS. ',
				autora: 'Deputada Laura Carneiro ',
				lei: 'Lei nº 10.894/2004',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=106924',
			},
			leg_104: {
				id: '104',
				ano: '2005',
				ementa: 'ALTERA O ART. 11 DA LEI Nº 8.069, DE 13 DE JULHO DE 1990, E DÁ OUTRAS PROVIDÊNCIAS. _NOVA EMENTADA REDAÇÃO FINAL: ALTERA O CAPUT DO ART. 11 DA  LEI Nº 8.069, DE 13 DE JULHO DE 1990, QUE DISPÕE SOBRE O ESTATUTO DA CRIANÇA E DO ADOLESCENTE E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Marinha Raupp',
				lei: 'Lei nº 11.185/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=105860',
			},
			leg_105: {
				id: '105',
				ano: '2005',
				ementa: 'MODIFICA OS ARTIGOS 216 E 231 DO DECRETO-LEI Nº 2.848, DE 7 DE DEZEMBRO DE 1940 - CÓDIGO PENAL, PARA SUPRIMIR O TERMO "MULHER HONESTA". NOVA EMENTA: ALTERA OS ARTIGOS 215, 216, 219, 220 E 231 E ACRESCENTA O ARTIGO 231 - A AO DECRETO-LEI Nº 2.848, DE 07 DE DEZEMBRO DE 1940 - CÓDIGO PENAL. NOVA EMENTA DA REDAÇÃO FINAL: ALTERA OS ARTIGOS 148, 215, 216, 226, 227 E 231 E ACRESCENTA O ARTIGO 231-A AO DECRETO-LEI Nº 2.848, DE 07 DE DEZEMBRO DE 1940 - CÓDIGO PENAL E DÁ OUTRAS ... ',
				autora: 'Deputada Iara Bernardi ',
				lei: 'Lei nº 11.106/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=104744',
			},
			leg_106: {
				id: '106',
				ano: '',
				ementa: 'ALTERA O ART. 129, DO DECRETO - LEI Nº 2.848, DE 7 DE DEZEMBRO DE 1940 - CÓDIGO PENAL, CRIANDO O TIPO ESPECIAL DENOMINADO "VIOLÊNCIA DOMÉSTICA" E DÁ OUTRAS PROVIDÊNCIAS. NOVA EMENTA DA REDAÇÃO FINAL: ACRESCENTA PARÁGRAFO AO ARTIGO 129, DO DECRETO - LEI Nº 2.848, DE 7 DE DEZEMBRO DE 1940 - CÓDIGO PENAL, CRIANDO O TIPO ESPECIAL DENOMINADO "VIOLÊNCIA DOMÉSTICA". ',
				autora: 'Deputada Iara Bernardi',
				lei: 'Lei nº 10.886/2004',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=104325',
			},
			leg_107: {
				id: '107',
				ano: '2002',
				ementa: 'ALTERA A RESOLUÇÃO Nº 38, DE 2001, DO SENADO FEDERAL (AUTORIZA O ESTADO DO RIO GRANDE DO SUL A ASSUMIR DÍVIDA DO INSTITUTO DE PREVIDÊNCIA DO ESTADO DO RIO GRANDE DO SUL (IPERGS), REFINANCIADA JUNTO À UNIÃO AO AMPARO DA LEI Nº 8727, DE 5 DE NOVEMBRO DE 1993, CUJO VALOR EM 1º DE NOVEMBRO DE 2000 ERA DE R$ 381.688.640,62 (TREZENTOS E OITENTA E UM MILHÕES, SEISCENTOS E  OITENTA E OITO MIL, SEISCENTOS E QUARENTA REAIS E SESSENTA E DOIS CENTAVOS). ',
				autora: 'Senadora Emília Fernandes ',
				lei: 'Lei nº 54/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/51692',
			},
			leg_108: {
				id: '108',
				ano: '2012',
				ementa: 'ALTERA A LEI Nº 9.656, DE 3 DE JUNHO DE 1998, PARA DISPOR SOBRE A OBRIGATORIEDADE DE FORNECIMENTO DE BOLSAS DE COLOSTOMIA PELOS PLANOS E SEGUROS PRIVADOS DE SAÚDE. NOVA EMENTA: ALTERA A LEI Nº 9.656, DE 3 DE JUNHO DE 1998, PARA TORNAR OBRIGATÓRIO O FORNECIMENTO DE BOLSAS DE COLOSTOMIA, ILEOSTOMIA E UROSTOMIA, DE COLETOR DE URINA E DE SONDA VESICAL PELOS PLANOS PRIVADOS DE ASSISTÊNCIA À SAÚDE.',
				autora: 'Deputada Jandira Feghali ',
				lei: 'Lei nº 12.738/2012',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=67377',
			},
			leg_109: {
				id: '109',
				ano: '2013',
				ementa: 'DISPÕE SOBRE A DENOMINAÇÃO DO NOVO PRÉDIO DA ADMINISTRAÇÃO DA FACULDADE DE DIREITO, NO CAMPUS DA UNIVERSIDADE FEDERAL DO AMAZONAS, NA CIDADE DE MANAUS.',
				autora: 'Deputada Vanessa Grazziotin ',
				lei: 'Lei nº 12.882/2013',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=67287',
			},
			leg_110: {
				id: '110',
				ano: '2002',
				ementa: 'DÁ NOVA REDAÇÃO AO ARTIGO 1º DA LEI Nº 662, DE 6 DE ABRIL DE 1949, QUE "DECLARA FERIADOS NACIONAIS OS DIAS 1º DE JANEIRO, 1º DE MAIO, 7 DE SETEMBRO, 15 DE NOVEMBRO E 25 DE DEZEMBRO", E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Senadora Vanessa Grazziotin ',
				lei: 'Lei nº 10.607/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/50570',
			},
			leg_111: {
				id: '111',
				ano: '2009',
				ementa: 'CRIA O RASTREAMENTO DA PRODUÇÃO E CONSUMO DE MEDICAMENTOS ATRAVÉS DO CONTROLE ELETRÔNICO POR CÓDIGOS DE BARRA. ',
				autora: 'Deputada Vanessa Grazziotin ',
				lei: 'Lei nº 11903/2009',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=50589',
			},
			leg_112: {
				id: '112',
				ano: '2002',
				ementa: 'DISPÕE SOBRE O LIMITE DE COMPROMETIMENTO DA RECEITA LÍQUIDA REAL DO ESTADO DO RIO GRANDE DO SUL, NO CONTEXTO DA IMPLEMENTAÇÃO CONTRATO DE QUE TRATA A RESOLUÇÃO Nº 64, DE 1998, DO SENADO FEDERAL.',
				autora: 'Senadora Heloísa Helena ',
				lei: 'Lei nº 10/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/49786',
			},
			leg_113: {
				id: '113',
				ano: '2005',
				ementa: 'INSCREVE O NOME DE JOSÉ BONIFÁCIO DE ANDRADA E SILVA NO LIVRO DOS HERÓIS DA PÁTRIA. ',
				autora: 'Deputada Telma De Souza',
				lei: 'Lei nº 11.135/2005',
				link: 'ttps://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=42516',
			},
			leg_114: {
				id: '114',
				ano: '2002',
				ementa: 'CRIA A COMISÃO PERMANENTE DE LEGISLAÇÃOPARTICIPATIVA NO SENADO FEDERAL.',
				autora: 'Senadora Marina Silva ',
				lei: 'Lei nº 64/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/48896',
			},
			leg_115: {
				id: '115',
				ano: '2005',
				ementa: 'DENOMINA "VIADUTO COLONIZADOR ÊNIO PIPINO" O VIADUTO SITUADO NO TREVO DE ACESSO À CIDADE DE SINOP - MT, NA BR-163. ',
				autora: 'Deputada Celcita',
				lei: 'Lei nº 11.256/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=33724',
			},
			leg_116: {
				id: '116',
				ano: '2008',
				ementa: 'DENOMINA RODOVIA GASPAR SILVEIRA MARTINS O TRECHO DA RODOVIA BR-153 QUE LIGA A CIDADE DE ACEGUÁ À RODOVIA BR-290, NO ESTADO DO RIO GRANDE DO SUL. ',
				autora: 'Senadora Emília Fernandes',
				lei: 'Lei nº 11.728/2008',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/47334',
			},
			leg_117: {
				id: '117',
				ano: '2003',
				ementa: 'ESTABELECE A NOTIFICAÇÃO COMPULSÓRIA DA VIOLÊNCIA CONTRA A MULHER ATENDIDA EM SERVIÇOS DE URGÊNCIA E EMERGÊNCIA E A CRIAÇÃO DA COMISSÃO DE MONITORAMENTO DA VIOLÊNCIA CONTRA A MULHER NO MINISTÉRIO DA SAÚDE E NAS SECRETARIAS ESTADUAIS DE SAÚDE. NOVA EMENTA: ESTABELECE A NOTIFICAÇÃO COMPULSÓRIA DA  VIOLÊNCIA CONTRA A MULHER, EM TODO O TERRITÓRIO NACIONAL, ATENDIDA EM SERVIÇOS DE SAÚDE PÚBLICOS OU PRIVADOS. ',
				autora: 'Deputada Socorro Gomes ',
				lei: 'Lei nº 10.778/2003',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=27775',
			},
			leg_118: {
				id: '118',
				ano: '2003',
				ementa: 'CONCEDE REMISSÃO DE DÉBITO PREVIDENCIÁRIO DO PERÍODO DE ABRIL DE 1994 A FEVEREIRO DE 1997, EM FACE DO RECOLHIMENTO COM BASE NA LEI Nº 8.870, DE 15 DE ABRIL DE 1994, PELAS AGROINDÚSTRIAS. ',
				autora: 'Deputada Kátia Abreu',
				lei: 'Lei nº 10.736/2003',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=27159',
			},
			leg_119: {
				id: '119',
				ano: '2020',
				ementa: 'CONFERE AO GOVERNADOR MÁRIO COVAS A DESIGNAÇÃO DE "PATRONO DO TURISMO NACIONAL". ',
				autora: 'Deputada Nair Xavier ',
				lei: 'Lei nº 10.471/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=26844',
			},
			leg_120: {
				id: '120',
				ano: '2005',
				ementa: 'INSTITUI O DIA 13 DE DEZEMBRO COMO O "DIA NACIONAL DO FORRÓ". ',
				autora: 'Deputada Luiza Erundina',
				lei: 'Lei nº 11.176/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=26760',
			},
			leg_121: {
				id: '121',
				ano: '2002',
				ementa: 'MODIFICA O PARÁGRAFO ÚNICO DO ART. 69 DA LEI Nº099, DE 26 DE SETEMBRO DE 1995.',
				autora: 'Deputada Nair Xavier Lobo',
				lei: 'Lei nº 10.455/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=20419',
			},
			leg_122: {
				id: '122',
				ano: '2002',
				ementa: 'DÁ NOVA REDAÇÃO AO ART. 1º DA LEI Nº 662, DE 6 DE ABRIL DE 1949, QUE "DECLARA FERIADOS NACIONAIS OS DIAS 1º DE JANEIRO, 1º DE MAIO, 7 DE SETEMBRO, 15 DE NOVEMBRO E 25 DE DEZEMBRO". ',
				autora: 'Deputada Vanessa Grazziotin',
				lei: 'Lei nº 10.607/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=20105',
			},
			leg_123: {
				id: '123',
				ano: '2005',
				ementa: 'DECLARA O ARQUITETO OSCAR NIEMAYER, PATRONO DA ARQUITETURA BRASILEIRA ',
				autora: 'Deputada Luiza Erundina ',
				lei: 'Lei nº 11.117/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=19613',
			},
			leg_124: {
				id: '124',
				ano: '2006',
				ementa: 'DISPÕE SOBRE O DIA DO PROFISSIONAL DE EDUCAÇÃO FÍSICA.',
				autora: 'Deputada Laura Carneiro',
				lei: 'Lei nº 11.342/2006',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=19208',
			},
			leg_125: {
				id: '125',
				ano: '2001',
				ementa: 'DISPÕE SOBRE A OBRIGATORIEDADE DA CIRURGIA PLÁSTICA REPARADORA DA MAMA POR PLANOS E SEGUROS PRIVADOS DE ASSISTÊNCIA À SAÚDE NOS CASOS DE MUTILAÇÃO DECORRENTES DE TRATAMENTO DE CÂNCER. NOVA EMENTA: ALTERA A LEI Nº 9.656, DE 03 DE JUNHO DE 1998, PARA DISPOR SOBRE A OBRIGATORIEDADE DE CIRURGIA PLÁSTICA REPARADORA DE MAMA POR PLANOS E SEGUROS PRIVADOS DE ASSISTÊNCIA À SAÚDE NOS CASOS DE MUTILAÇÃO DECORRENTE DE TRATAMENTO DE CÂNCER. ',
				autora: 'Deputada Jandira Feghali ',
				lei: 'Lei nº 10.223/2001',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=19115',
			},
			leg_126: {
				id: '126',
				ano: '2005',
				ementa: 'DÁ NOVA REDAÇÃO AO INCISO II DO ART. 20 DA LEI Nº .394, DE 20 DE DEZEMBRO DE 1996, QUE "ESTABELECE AS DIRETRIZES E BASES DA EDUCAÇÃO NACIONAL". NOVA EMENTA DA REDAÇÃO FINAL: DÁ NOVA REDAÇÃO AO INCISO II DO CAPUT DO ART. 20 DA LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, QUE ESTABELECE AS DIRETRIZES E BASES DA EDUCAÇÃO NACIONAL. ... ',
				autora: 'Deputada Celcita Pinheiro',
				lei: 'Lei nº 11.183/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=18209',
			},
			leg_127: {
				id: '127',
				ano: '2002',
				ementa: 'DENOMINA "VIADUTO LUIZ PHILIPPE PEREIRA LEITE" O VIADUTO LOCALIZADO NO QUILÔMETRO 404 DA RODOVIA BR-364/163, NO ENTRONCAMENTO COM A RODOVIA MT-407, RODOVIA DOS IMIGRANTES, NO MUNICÍPIO DE CUIABÁ-MT. ',
				autora: 'Deputada Celcita Pinheiro',
				lei: 'Lei nº 10.423/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=18118',
			},
			leg_128: {
				id: '128',
				ano: '2004',
				ementa: 'ALTERA O ART. 25 DA LEI Nº 8171, DE 17 DE JANEIRO DE 1991, QUE "DISPÕE SOBRE A POLÍTICA AGRÍCOLA".  ',
				autora: 'Senadora Maria Do Carmo Alves',
				lei: 'Lei nº 10.990/2004',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/42829',
			},
			leg_129: {
				id: '129',
				ano: '2010',
				ementa: 'DISPÕE SOBRE A PUBLICAÇÃO ANUAL, PELO PODER EXECUTIVO, DAS ATIVIDADES SOCIAIS RELATIVAS À MULHER. ',
				autora: 'Deputada Luiza Erundina',
				lei: 'Lei nº 12.227/2010',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=17715',
			},
			leg_130: {
				id: '130',
				ano: '2005',
				ementa: 'DISPÕE SOBRE A OBRIGATORIEDADE DE INSTALAÇÃODE BRINQUEDOTECAS NOS HOSPITAIS DA REDE PÚBLICA.',
				autora: 'Deputada Luiza Erundina',
				lei: 'Lei nº 11.104/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=17616',
			},
			leg_131: {
				id: '131',
				ano: '2009',
				ementa: 'INSTITUI O DIA NACIONAL DO INVENTOR E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Senadora Maria Do Carmo Alves',
				lei: 'Lei nº 12.070/2009',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/42523',
			},
			leg_132: {
				id: '132',
				ano: '2001',
				ementa: 'ALTERA A LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, QUE ESTABELECE AS DIRETRIZES E BASES DA EDUAÇÃO NACIONAL.',
				autora: 'Deputada Miriam Reid ',
				lei: 'Lei 10.287/2001',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=17385',
			},
			leg_133: {
				id: '133',
				ano: '2012',
				ementa: 'DISPÕE SOBRE A ELABORAÇÃO E ARQUIVAMENTO DE DOCUMENTOS EM MEIOS ELETROMAGNÉTICOS.',
				autora: 'Deputada Angela Guadagnin ',
				lei: 'Lei nº 12.682/2012',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=16863',
			},
			leg_134: {
				id: '134',
				ano: '2003',
				ementa: 'ALTERA A REDAÇÃO DO ART. 26, § 3º, E DO ART. 92 DA LEI Nº 9.394, DE 20 DE DEZEMBRO DE 1996, QUE "ESTABELECE AS DIRETRIZES E BASES DA EDUCAÇÃO NACIONAL", E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Dr. Rosinha PR ',
				lei: 'Lei nº 10.793/2003',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=16769',
			},
			leg_135: {
				id: '135',
				ano: '2002',
				ementa: 'INSTITUI O 12 DE AGOSTO COMO DIA NACIONAL DA JUVENTUDE.',
				autora: 'Deputada Alcione Athayde',
				lei: 'Lei nº 10.515/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=16720',
			},
			leg_136: {
				id: '136',
				ano: '2004',
				ementa: 'INSCREVE O NOME DE CHICO MENDES NO "LIVRO DOS HERÓIS DA PÁTRIA".',
				autora: 'Senadora Marina ',
				lei: 'Lei nº 10.952/2004',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/40496',
			},
			leg_137: {
				id: '137',
				ano: '2000',
				ementa: 'ACRESCENTA ARTIGO À LEI Nº 8.069, DE 1990, QUE DISPÕE SOBRE O ESTATUTO DA CRIANÇA E DO ADOLESCENTE.',
				autora: 'Deputada Luiza Erundina De Sousa',
				lei: 'Lei nº 9.975/2000',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=38153',
			},
			leg_138: {
				id: '138',
				ano: '2004',
				ementa: 'DÁ A DENOMINAÇÃO DE "AEROPORTO DE SÃO JOSÉ DOS CAMPOS - PROFESSOR URBANO ERNESTO STUMPF" AO AEROPORTO DA CIDADE DE SÃO JOSÉ DOS CAMPOS, ESTADO DE SÃO PAULO.',
				autora: 'Deputada Angela Guadagnin ',
				lei: 'Lei nº 10.968/2004',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15256',
			},
			leg_139: {
				id: '139',
				ano: '2000',
				ementa: 'DISPÕE SOBRE A INSTITUIÇÃO DO DIA 18 DE MAIO COMO O DIA NACIONAL DE COMBATE AO ABUSO E EXPLORAÇÃO SEXUAL DE CRIANÇAS E ADOLESCENTES. ',
				autora: 'Deputada Rita Camata ',
				lei: 'Lei nº 9.970/2000',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=38151',
			},
			leg_140: {
				id: '140',
				ano: '2003',
				ementa: 'ALTERA OS ARTIGOS 240 E 241 DA LEI 8069, DE 13 DE JULHO DE 1990 - ESTATUTO DA CRIANÇA E DO ADOLESCENTE.',
				autora: 'Senadora Marina Silva ',
				lei: 'Lei nº 10.764/2003',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/1421',
			},
			leg_141: {
				id: '141',
				ano: '2003',
				ementa: 'DISPÕE SOBRE A OBRIGATORIEDADE DA INCLUSÃO, NO CURRÍCULO OFICIAL DA REDE DE ENSINO, DA TEMATICA "HISTÓRIA E CULTURA AFRO-BRASILEIRA" E DÁ OUTRAS PROVIDÊNCIAS. ',
				autora: 'Deputada Esther Grossi e Ben-Hur Ferreira',
				lei: 'Lei nº 10.639/2003',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15223',
			},
			leg_142: {
				id: '142',
				ano: '2002',
				ementa: 'INSTITUI O DIA NACIONAL DE LUTA PELA REFORMA AGRARIA E DA OUTRAS PROVIDENCIAS. ',
				autora: 'Senadora Marina Silva ',
				lei: 'Lei nº 10.469/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/1358 ',
			},
			leg_143: {
				id: '143',
				ano: '2003',
				ementa: 'AUTORIZA O PODER EXECUTIVO A DISPONIBILIZAR, EM NIVEL NACIONAL, NUMERO TELEFONICO DESTINADO A ATENDER DENUNCIAS DE VIOLENCIA CONTRA A MULHER.',
				autora: 'Senadora Emília Fernandes',
				lei: 'Lei nº 10.714/2003',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/1330',
			},
			leg_144: {
				id: '144',
				ano: '2005',
				ementa: 'ALTERA O ART. 101 DA LEI Nº 8.069, DE 13 DE JULHO DE 1990 - ESTATUTO DA CRIANÇA E DO ADOLESCENTE - DETERMINANDO INVESTIGAÇÃO IMEDIATA EM CASO DE DESAPARECIMENTO DE CRIANÇA E ADOLESCENTE, E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Maria Elvira',
				lei: 'Lei nº 11.259/2005',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15055',
			},
			leg_145: {
				id: '145',
				ano: '2002',
				ementa: 'DISPÕE SOBRE A COMERCIALIZAÇÃO DE PRESERVATIVOS MASCULINOS DE LÁTEX DE BORRACHA.',
				autora: 'Deputada Maria Elvira ',
				lei: 'Lei nº 10.449/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15048',
			},
			leg_146: {
				id: '146',
				ano: '2001',
				ementa: 'DISPÕE SOBRE O CRIME DE ASSÉDIO SEXUAL E DÁ OUTRAS PROVIDÊNCIAS. ',
				autora: 'Deputada Iara Bernardi',
				lei: 'Lei nº 10.224/2001',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=14995',
			},
			leg_147: {
				id: '147',
				ano: '2013',
				ementa: 'DISPÕE SOBRE O ATENDIMENTO ÀS VÍTIMAS DE VIOLÊNCIA SEXUAL. NOVA EMENTA: DISPÕE SOBRE O ATENDIMENTO OBRIGATÓRIO E INTEGRAL DE PESSOAS EM SITUAÇÃO DE VIOLÊNCIA SEXUAL.',
				autora: 'Deputada Iara Bernardi',
				lei: 'Lei nº 12.845/2013',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=14993',
			},
			leg_148: {
				id: '148',
				ano: '2012',
				ementa: 'DISPÕE SOBRE O INGRESSO NAS UNIVERSIDADES FEDERAIS E ESTADUAIS E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Nice Lobão ',
				lei: 'Lei nº 12.711/2012',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15013',
			},
			leg_149: {
				id: '149',
				ano: '1999',
				ementa: 'DISPÕE SOBRE A OBRIGATORIEDADE DA CIRURGIA PLÁSTICA REPARADORA DA MAMA PELA REDE DE UNIDADES INTEGRANTES DO SISTEMA ÚNICO DE SAÚDE- SUS- NOS CASOS DE MUTILAÇÃO DECORRENTES DE TRATAMENTO DE CÂNCER.',
				autora: 'Deputada Maria Elvira ',
				lei: 'Lei nº 9.797/1999',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=38107',
			},
			leg_150: {
				id: '150',
				ano: '2001',
				ementa: 'INSTITUI A SEMANA NACIONAL DE COMBATE E PREVENÇÃO AO CÂNCER DE PRÓSTATA.',
				autora: 'Deputada Telma De Souza ',
				lei: 'Lei nº 10.289/2001',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=19765',
			},
			leg_151: {
				id: '151',
				ano: '1999',
				ementa: 'PROJETO DE LEI QUE DISPÕE SOBRE A RECLAMAÇÃO AO SUPREMO TRIBUNAL FEDERAL EM CASO DE DESCUMPRIMENTO DE PRECEITO CONSTITUCIONAL NO PROCESSO LEGISLATIVO E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Sandra Starling ',
				lei: 'Lei nº 9.882/1999',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=41078',
			},
			leg_152: {
				id: '152',
				ano: '1999',
				ementa: 'DENOMINA FLORESTAN FERNANDES A SALA DA COMISSÃO DE ASSUNTOS SOCIAIS. ',
				autora: 'Senadora Marina Silva',
				lei: 'Lei nº 30/1999',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/1790',
			},
			leg_153: {
				id: '153',
				ano: '1999',
				ementa: 'ESTABELECE A FACULDADE DE O CONSUMIDOR E O USUARIO DETERMINAREM A DATA DE VENCIMENTO DE SEUS DEBITOS.',
				autora: 'Deputada Vanessa Felippe ',
				lei: 'Lei nº 9.791/99',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=200030',
			},
			leg_154: {
				id: '154',
				ano: '2002',
				ementa: 'DISPÕE SOBRE A LÍNGUA BRASILEIRA DE SINAIS E DÁ OUTRAS PROVIDÊNCIAS.',
				autora: 'Senadora Benedita Da Silva',
				lei: 'Lei nº 10.436/2002',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/1405',
			},
			leg_155: {
				id: '155',
				ano: '1999',
				ementa: 'ALTERA DISPOSITIVOS DA LEI 8666, DE 21 DE JUNHO DE1993, QUE REGULAMENTA O ARTIGO 37 INCISO XXI DA CONSTITUIÇÃO FEDERAL INSTITUI NORMAS PARA LICITAÇÕES E CONTRATOS DA ADMINISTRAÇÃO PUBLICA E DA OUTRAS PROVIDENCIAS ',
				autora: 'Deputada Rita Camata',
				lei: 'Lei nº 9.854/1999',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=197346',
			},
			leg_156: {
				id: '156',
				ano: '2002',
				ementa: 'DÁ NOVA REDAÇÃO AO ARTIGO 392 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO, APROVADA PELO DECRETO-LEI Nº 5.452, DE 1º DE MAIO DE 1943.NOVA EMENTA DO SUBSTITUTIVO: ESTENDE À MÃE  ADOTIVA O DIREITO À LICENÇA-MATERNIDADE E AO SALÁRIO-MATERNIDADE, ALTERANDO A CONSOLIDAÇÃO DAS LEIS DO TRABALHO, APROVADA PELO DECRETO-LEI Nº 5.452, DE 1º DE MAIO DE 1943, E A LEI Nº 8.213, DE 24 DE JULHO DE ... ',
				autora: 'Deputada Fátima Pelaes',
				lei: 'Lei nº 10.421/2002',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=17146',
			},
			leg_157: {
				id: '157',
				ano: '2001',
				ementa: 'DÁ NOVA REDAÇÃO AO PARÁGRAFO 2º DO ARTIGO 17DA CONSTITUIÇÃO FEDERAL. NOVA EMENTA DA  REDAÇÃO DO VENCIDO: DÁ NOVA REDAÇÃO À ALÍNEA "C" DO INCISO XVI DO ART. 37 DA CONSTITUIÇÃO FEDERAL.',
				autora: 'Deputada Jandira Feghali ',
				lei: 'Lei nº 34/2001',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=14694',
			},
			leg_158: {
				id: '158',
				ano: '1996',
				ementa: 'INSCREVE O NOME DE ZUMBI DOS PALMARES NO LIVRO DOS HEROIS DA PATRIA ',
				autora: 'Senadora Benedita Da Silva ',
				lei: 'Lei nº 9.315/1996 ',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/29901',
			},
			leg_159: {
				id: '159',
				ano: '2009',
				ementa: 'DÁ NOVA REDAÇÃO AO ART. 89 DA LEI Nº 7.210, DE 11 DE JULHO DE 1984 (LEI DE EXECUÇÃO PENAL), QUE TRATA DAS PENITENCIÁRIAS DE MULHERES.',
				autora: 'Deputada Fátima Pelaes ',
				lei: 'Lei nº 11.942/2009 ',
				link: 'https: //www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=15320',
			}, 
			leg_160: {
				id: '160',
				ano: '1997',
				ementa: 'DISPÕE SOBRE O EXERCICIO DO DIREITO DE QUEIXA PELA MULHER.',
				autora: 'Deputada Raquel Capiberibe',
				lei: 'Lei nº 9.520/1997',
				link: 'https: //www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=173695',
			}, 
			leg_161: {
				id: '161',
				ano: '161',
				ementa: 'ACRESCENTA INCISO AO ARTIGO 473 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO.',
				autora: 'Deputada Rita Camata',
				lei: 'Lei nº 9.471/1997',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=170806',
			},
			leg_162: {
				id: '162',
				ano: '1998',
				ementa: 'ACRESCENTA PARAGRAFOS AO ARTIGO 11 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO E DETERMINA OUTRAS PROVIDENCIAS.',
				autora: 'Deputada Rita Camata',
				lei: 'Lei nº 9.658/1998',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=170760',
			},
			leg_163: {
				id: '163',
				ano: '1995',
				ementa: 'PROIBE A EXIGÊNCIA DE ATESTADOS DE GRAVIDEZ E ESTERILIZAÇÃO, E OUTRAS PRÁTICAS DISCRIMINATÓRIAS, PARA EFEITOS ADMISSIONAIS OU DE PERMANÊNCIA DA RELAÇÃO JURÍDICA DE TRABALHO, E DA OUTRAS PROVIDÊNCIAS.',
				autora: 'Deputada Benedita Da Silva',
				lei: 'Lei nº 9.029/1995',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/21487',
			},
			leg_164: {
				id: '164',
				ano: '1996',
				ementa: 'REVOGA OS PARAGRAFOS UNICOS DOS ARTS. 213 E 14 DO DECRETO-LEI 2848 DE 07 DE DEZEMBRO DE  1940 - CODIGO PENAL.',
				autora: 'Senadora Rose De Freitas ',
				lei: 'Lei nº 9.281/1996',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/19202',
			},
			leg_165: {
				id: '165',
				ano: '1995',
				ementa: 'ALTERA O ARTIGO 83 DA LEI 7210, DE 11 DE JULHO DE 1984 - LEI DE EXECUÇÃO PENAL. ',
				autora: 'Senadora Benedita Da Silva ',
				lei: 'Lei nº 9.046/1995',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/20400',
			},
			leg_166: {
				id: '166',
				ano: '1998',
				ementa: 'DISPÕE SOBRE A INCLUSÃO DO VALE DO JEQUITINHONHA DO ESTADO DE MINAS GERAIS NA AREA DE ATUAÇÃO DA SUPERINTENCIA DO  DESENVOLVIMENTO DO NORDESTE - SUDENE.',
				autora: 'Senadora Junia Marise',
				lei: 'Lei nº 9.690/1998',
				link: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/28397',
			},
			leg_168: {
				id: '168',
				ano: '1994',
				ementa: 'ESTENDE AOS EDUCANDOS DAS APAES E AOS EDUCANDOS QUE RECEBAM ATENDIMENTO ESPECIALIZADO O DISPOSTO NOS ARTIGOS PRIMEIRO, QUARTO E QUINTO DA LEI Nº 6.494, DE 07 DE DEZEMBRO DE 1977 E DA OUTRAS PROVIDENCIAS.',
				autora: 'Deputada Angela Amin ',
				lei: 'Lei nº 8.859/1994',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=208898',
			},
			leg_169: {
				id: '169',
				ano: '1996',
				ementa: 'REGULAMENTA O PARAGRAFO TERCEIRO DO ARTIGO226 DA CONSTITUIÇÃO FEDERAL.',
				autora: 'Deputada Beth Azize ',
				lei: 'Lei nº 9.278/1996',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=197334',
			},
			leg_170: {
				id: '170',
				ano: '1996',
				ementa: 'ALTERA OS ARTIGOS 213 E 214 DO DECRETO-LEI Nº2.848, DE 07 DE DEZEMBRO DE 1940 - CÓDIGO PENAL ',
				autora: 'Deputada Rose De Freitas ',
				lei: 'Lei nº 9.281/1996',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=25220',
			},
			leg_171: {
				id: '171',
				ano: '1994',
				ementa: 'DISPÕE SOBRE A PARTICIPAÇÃO DO PROPRIETARIO DO SOLO NOS RESULTADOS DA LAVRA DE RECURSOS MINERAIS.',
				autora: 'Deputada Rita Camata ',
				lei: 'Lei nº 8.901/1994',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=186156',
			},
			leg_172: {
				id: '172',
				ano: '1995',
				ementa: 'DISPÕE SOBRE A CONSTRUÇÃO DE CRECHES E ESTABELECIMENTOS DE PRE-ESCOLA. ',
				autora: 'Deputada Marilu Guimarães',
				lei: 'Lei nº 8.978/1995',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=178822',
			},
			leg_173: {
				id: '173',
				ano: '1992',
				ementa: 'REAJUSTA A PENSÃO ESPECIAL MENSAL CONCEDIDA AS VIUVAS DE EX-PRESIDENTES DA REPUBLICA. ',
				autora: 'Deputada Sandra Cavalcanti',
				lei: 'Lei nº 8.400/1992',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=176259',
			},
			leg_174: {
				id: '174',
				ano: '1995',
				ementa: 'PROIBE A EXIGENCIA DE ATESTADO QUE COMPROVE ESTERILIDADE OU GRAVIDEZ DE CANDIDATOS A EMPREGO.',
				autora: 'Deputada Benedita Da Silva',
				lei: 'Lei nº 9.029/1995',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=173499',
			},
			leg_175: {
				id: '175',
				ano: '1999',
				ementa: 'DISPÕE SOBRE O ACESSO AO MERCADO DE TRABALHO E DETERMINA OUTRAS PROVIDÊNCIAS. ',
				autora: 'Deputada Rita Camata ',
				lei: 'Lei nº 9.799/1999',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=25087',
			},
			leg_176: {
				id: '176',
				ano: '1993',
				ementa: 'DISPÕE SOBRE A REGULAMENTAÇÃO DOS DISPOSITIVOS CONSTITUCIONAIS RELATIVOS A REFORMA AGRARIA, PREVISTOS NO CAPITULO III,  ITULO VII, DA CONSTITUIÇÃO FEDERAL.',
				autora: 'Deputada Luci Choinacki ',
				lei: 'Lei nº 8.629/1993',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=170088',
			},
			leg_177: {
				id: '177',
				ano: '1995',
				ementa: 'ALTERA O ARTIGO 83, DA LEI 7210, DE 11 DE JULHO DE 1984, LEI DE EXECUÇÃO PENAL. ',
				autora: 'Deputada Benedita Da Silva ',
				lei: 'Lei nº 9.046/1995',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=202552',
			},
			leg_178: {
				id: '178',
				ano: '1994',
				ementa: 'CRIA AREAS DE LIVRE COMERCIO NOS MUNICIPIOS DE BRASILEIA, CRUZEIRO DO SUL E PLACIDO DE CASTRO, NO ESTADO DO ACRE E DA OUTRAS PROVIDENCIAS.',
				autora: 'Deputada Zila Bezerra',
				lei: 'Lei nº 8.857/1994',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=202497',
			},
			leg_179: {
				id: '179',
				ano: '1993',
				ementa: 'REVOGA A LEI 3252, DE 27 DE AGOSTO DE 1957 EIS PÕE SOBRE A REGULAMENTAÇÃO DA PROFISSÃO DE ASSISTENTE SOCIAL.',
				autora: 'Deputada Benedita Da Silva',
				lei: 'Lei nº 8.662/1993',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=216988',
			},
			leg_180: {
				id: '180',
				ano: '1994',
				ementa: 'DA NOVA REDAÇÃO AO ARTIGO 392 DA CONSOLIDAÇÃO DAS LEIS DO TRABALHO.',
				autora: 'Deputada Rita Camata',
				lei: 'Lei nº 8.861/1994',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=197064',
			},
			leg_181: {
				id: '181',
				ano: '1985',
				ementa: 'REVOGA A LEI 5465, DE 03 DE JULHO DE 1968, QUE DISPÕE SOBRE O PREENCHIMENTO DE VAGAS NO ENSINO AGRICOLA ASSIM COMO SUA LEGISLAÇÃO COMPLEMENTAR.',
				autora: 'Deputada Cristina Tavares',
				lei: 'Lei nº 7.423/1985',
				link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=181717',
			},
			leg_182: {
				id: '182',
				ano: '1985',
			ementa: 'DISPÕE SOBRE A CRIAÇÃO DO COLEGIO AGRICOLA DE GARANHUNS, NO ESTADO DE PERNAMBUCO.',
			autora: 'Deputada Cristina Tavares ',
			lei: 'Lei nº 7.304/1985',
			link: 'https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=220820',
		},


	}

	function montar_legislacao() {

		for (x in legislacoes) {

			legislacao =
				'<div id="leg_' + legislacoes[x].id + '" class="leg_item ' + legislacoes[x].ano + '">' +
				'<a href="' + legislacoes[x].link + '" target="_blank">' +
				legislacoes[x].lei +
				'</a>' +
				'<p>' + legislacoes[x].ementa + '</p>' +
				'<span>' + legislacoes[x].autora + '</span>' +
				'</div>';


			// str1 = "#noticia_";

			// $(sigla = str1.concat(noticias[x].id.toLowerCase())).prepend(noticia);

			$("#leg-" + legislacoes[x].ano + " .card-body").append(legislacao);


		}


	}

	montar_legislacao();

    });